/*******************************************************************************
 * Copyright (c) 2013-2015 UAH Space Research Group.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     MICOBS SRG Team - Initial API and implementation
 ******************************************************************************/
package es.uah.aut.srg.micobs.mclev.domain.edroom.edroomprot.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import es.uah.aut.srg.micobs.mclev.domain.edroom.edroomprot.util.edroomprotAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 *
 * @generated
 */
public class edroomprotItemProviderAdapterFactory extends edroomprotAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * @generated
	 */
	public edroomprotItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomprot.EDROOMProtocol} instances.
	 * @generated
	 */
	protected EDROOMProtocolItemProvider edroomProtocolItemProvider;

	/**
	 * This creates an adapter for a {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomprot.EDROOMProtocol}.
	 * @generated
	 */
	@Override
	public Adapter createEDROOMProtocolAdapter() {
		if (edroomProtocolItemProvider == null) {
			edroomProtocolItemProvider = new EDROOMProtocolItemProvider(this);
		}

		return edroomProtocolItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomprot.EDROOMSendMessage} instances.
	 * @generated
	 */
	protected EDROOMSendMessageItemProvider edroomSendMessageItemProvider;

	/**
	 * This creates an adapter for a {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomprot.EDROOMSendMessage}.
	 * @generated
	 */
	@Override
	public Adapter createEDROOMSendMessageAdapter() {
		if (edroomSendMessageItemProvider == null) {
			edroomSendMessageItemProvider = new EDROOMSendMessageItemProvider(this);
		}

		return edroomSendMessageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomprot.EDROOMInvokeMessage} instances.
	 * @generated
	 */
	protected EDROOMInvokeMessageItemProvider edroomInvokeMessageItemProvider;

	/**
	 * This creates an adapter for a {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomprot.EDROOMInvokeMessage}.
	 * @generated
	 */
	@Override
	public Adapter createEDROOMInvokeMessageAdapter() {
		if (edroomInvokeMessageItemProvider == null) {
			edroomInvokeMessageItemProvider = new EDROOMInvokeMessageItemProvider(this);
		}

		return edroomInvokeMessageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomprot.EDROOMReplyMessage} instances.
	 * @generated
	 */
	protected EDROOMReplyMessageItemProvider edroomReplyMessageItemProvider;

	/**
	 * This creates an adapter for a {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomprot.EDROOMReplyMessage}.
	 * @generated
	 */
	@Override
	public Adapter createEDROOMReplyMessageAdapter() {
		if (edroomReplyMessageItemProvider == null) {
			edroomReplyMessageItemProvider = new EDROOMReplyMessageItemProvider(this);
		}

		return edroomReplyMessageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomprot.EDROOMPROTPackageFile} instances.
	 * @generated
	 */
	protected EDROOMPROTPackageFileItemProvider edroomprotPackageFileItemProvider;

	/**
	 * This creates an adapter for a {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomprot.EDROOMPROTPackageFile}.
	 * @generated
	 */
	@Override
	public Adapter createEDROOMPROTPackageFileAdapter() {
		if (edroomprotPackageFileItemProvider == null) {
			edroomprotPackageFileItemProvider = new EDROOMPROTPackageFileItemProvider(this);
		}

		return edroomprotPackageFileItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory.
	 * @generated
	 */
	public void dispose() {
		if (edroomProtocolItemProvider != null) edroomProtocolItemProvider.dispose();
		if (edroomSendMessageItemProvider != null) edroomSendMessageItemProvider.dispose();
		if (edroomInvokeMessageItemProvider != null) edroomInvokeMessageItemProvider.dispose();
		if (edroomReplyMessageItemProvider != null) edroomReplyMessageItemProvider.dispose();
		if (edroomprotPackageFileItemProvider != null) edroomprotPackageFileItemProvider.dispose();
	}

}
