<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="edroomprot" nsURI="http://srg.aut.uah.es/micobs/mclev/domain/edroom/edroomprot"
    nsPrefix="micobs.mclev.domain.edroom">
  <eClassifiers xsi:type="ecore:EClass" name="EDROOMProtocol" eSuperTypes="#//EDROOMPROTPackageElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputMessages" upperBound="-1"
        eType="#//EDROOMMessage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputMessages" upperBound="-1"
        eType="#//EDROOMMessage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" upperBound="-1"
        eType="#//EDROOMProtocol"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EDROOMMessage" abstract="true" eSuperTypes="../../es.uah.aut.srg.micobs/model/common.ecore#//MCommonReferenceableObj">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataClass" eType="ecore:EClass dclass.ecore#//EDROOMDataClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EDROOMSendMessage" eSuperTypes="#//EDROOMMessage"/>
  <eClassifiers xsi:type="ecore:EClass" name="EDROOMInvokeMessage" eSuperTypes="#//EDROOMMessage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="replies" lowerBound="1"
        upperBound="-1" eType="#//EDROOMReplyMessage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EDROOMReplyMessage" eSuperTypes="#//EDROOMMessage"/>
  <eClassifiers xsi:type="ecore:EClass" name="EDROOMPROTPackageFile" eSuperTypes="../../es.uah.aut.srg.micobs/model/common.ecore#//MCommonPackageFile"/>
  <eClassifiers xsi:type="ecore:EClass" name="EDROOMPROTPackageElement" abstract="true"
      eSuperTypes="../../es.uah.aut.srg.micobs/model/common.ecore#//MCommonPackageReferencingElement"/>
</ecore:EPackage>
