<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mclevflatmcad" nsURI="http://srg.aut.uah.es/micobs/mclev/mclevflatmcad"
    nsPrefix="micobs.mclev">
  <eClassifiers xsi:type="ecore:EClass" name="MFlatMCAD" eSuperTypes="#//MMCLEVFLATMCADPackageElement ../../es.uah.aut.srg.micobs/model/common.ecore#//MCommonPackageReferencingElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targets" lowerBound="1"
        upperBound="-1" eType="#//MFlatMCADTarget" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MFlatMCADTarget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deploymentPlatform" lowerBound="1"
        eType="ecore:EClass mcad.ecore#//MDeploymentPlatform"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leafDeploymentAlternative"
        eType="ecore:EClass mcad.ecore#//MDeploymentAlternative"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeValueAssignments"
        upperBound="-1" eType="ecore:EClass ../../es.uah.aut.srg.micobs/model/common.ecore#//MParameterValueAssignment"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="libraries" upperBound="-1"
        eType="#//MFlatServiceLibraryInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//MFlatComponentInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connections" upperBound="-1"
        eType="#//MFlatConnection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MFlatServiceLibraryInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="library" lowerBound="1"
        eType="ecore:EClass slib.ecore#//MServiceLibrary"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeValueAssignments"
        upperBound="-1" eType="ecore:EClass ../../es.uah.aut.srg.micobs/model/common.ecore#//MParameterValueAssignment"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MFlatDriverSLibInstance" eSuperTypes="#//MFlatServiceLibraryInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deviceDriverMappings" upperBound="-1"
        eType="#//MFlatDeviceDriverMapping" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MFlatComponentInstance" eSuperTypes="../../es.uah.aut.srg.micobs/model/common.ecore#//MCommonReferenceableObj">
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        eType="ecore:EClass cmp.ecore#//MComponent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeValueAssignments"
        upperBound="-1" eType="ecore:EClass ../../es.uah.aut.srg.micobs/model/common.ecore#//MParameterValueAssignment"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MFlatConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="clientInstance" lowerBound="1"
        eType="#//MFlatComponentInstance" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clientPort" lowerBound="1"
        eType="ecore:EClass cmp.ecore#//MClientPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serverInstance" lowerBound="1"
        eType="#//MFlatComponentInstance" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serverPort" lowerBound="1"
        eType="ecore:EClass cmp.ecore#//MServerPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connector" lowerBound="1"
        eType="ecore:EClass dom.ecore#//MConnector"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifaceMapping" eType="ecore:EClass imap.ecore#//MInterfaceMapping"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeValueAssignments"
        upperBound="-1" eType="ecore:EClass ../../es.uah.aut.srg.micobs/model/common.ecore#//MParameterValueAssignment"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVFLATMCADPackageFile" eSuperTypes="../../es.uah.aut.srg.micobs/model/common.ecore#//MCommonPackageFile"/>
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVFLATMCADPackageElement" abstract="true"
      eSuperTypes="../../es.uah.aut.srg.micobs/model/common.ecore#//MCommonPackageElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="MFlatDeviceDriverMapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deployedDevice" lowerBound="1"
        eType="ecore:EClass mcad.ecore#//MDeployedDevice"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedDevice" lowerBound="1"
        eType="ecore:EClass slib.ecore#//MDriverSLibSupportedDevice"/>
  </eClassifiers>
</ecore:EPackage>
