<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mclevmcad" nsURI="http://srg.aut.uah.es/micobs/mclev/mclevmcad"
    nsPrefix="micobs.mclev">
  <eClassifiers xsi:type="ecore:EClass" name="MMCADeployment" eSuperTypes="#//MMCLEVMCADPackageElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="domain" lowerBound="1"
        eType="ecore:EClass dom.ecore#//MDomain"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="libraries" upperBound="-1"
        eType="#//MServiceLibraryInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//MComponentInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeValueAssignments"
        upperBound="-1" eType="ecore:EClass ../../es.uah.aut.srg.micobs/model/common.ecore#//MParameterValueAssignment"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deploymentAlternatives"
        upperBound="-1" eType="#//MDeploymentAlternative" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connections" upperBound="-1"
        eType="#//MConnection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deploymentPlatforms" upperBound="-1"
        eType="#//MDeploymentPlatform" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MServiceLibraryInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="library" lowerBound="1"
        eType="ecore:EClass slib.ecore#//MServiceLibrary"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeValueAssignments"
        upperBound="-1" eType="ecore:EClass ../../es.uah.aut.srg.micobs/model/common.ecore#//MParameterValueAssignment"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MDriverSLibInstance" eSuperTypes="#//MServiceLibraryInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deviceDriverMappings" upperBound="-1"
        eType="#//MDeviceDriverMapping" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MDeviceDriverMapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deployedDevice" lowerBound="1"
        eType="#//MDeployedDevice"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedDevice" lowerBound="1"
        eType="ecore:EClass slib.ecore#//MDriverSLibSupportedDevice"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MComponentInstance" eSuperTypes="../../es.uah.aut.srg.micobs/model/common.ecore#//MCommonReferenceableObj">
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        eType="ecore:EClass cmp.ecore#//MComponent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeValueAssignments"
        upperBound="-1" eType="ecore:EClass ../../es.uah.aut.srg.micobs/model/common.ecore#//MParameterValueAssignment"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MDeploymentAlternative" eSuperTypes="../../es.uah.aut.srg.micobs/model/common.ecore#//MCommonReferenceableObj">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deploymentPlatforms" upperBound="-1"
        eType="#//MDeploymentPlatform"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeValueAssignments"
        upperBound="-1" eType="ecore:EClass ../../es.uah.aut.srg.micobs/model/common.ecore#//MParameterValueAssignment"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="libraries" upperBound="-1"
        eType="#//MServiceLibraryInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//MComponentInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deploymentAlternatives"
        upperBound="-1" eType="#//MDeploymentAlternative" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connections" upperBound="-1"
        eType="#//MConnection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MConnection" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="MCommonConnection" eSuperTypes="#//MConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="clientInstance" lowerBound="1"
        eType="#//MComponentInstance" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clientPort" lowerBound="1"
        eType="ecore:EClass cmp.ecore#//MClientPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serverInstance" lowerBound="1"
        eType="#//MComponentInstance" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serverPort" lowerBound="1"
        eType="ecore:EClass cmp.ecore#//MServerPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connector" lowerBound="1"
        eType="ecore:EClass dom.ecore#//MConnector"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifaceMapping" eType="ecore:EClass imap.ecore#//MInterfaceMapping"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeValueAssignments"
        upperBound="-1" eType="ecore:EClass ../../es.uah.aut.srg.micobs/model/common.ecore#//MParameterValueAssignment"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MConnectionSwitch" eSuperTypes="#//MConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="clientInstance" lowerBound="1"
        eType="#//MComponentInstance" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clientPort" lowerBound="1"
        eType="ecore:EClass cmp.ecore#//MClientPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cases" lowerBound="1" upperBound="-1"
        eType="#//MConnectionSwitchCase" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MConnectionSwitchCase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alternative" lowerBound="1"
        eType="#//MDeploymentAlternative"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serverInstance" lowerBound="1"
        eType="#//MComponentInstance" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serverPort" lowerBound="1"
        eType="ecore:EClass cmp.ecore#//MServerPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connector" lowerBound="1"
        eType="ecore:EClass dom.ecore#//MConnector"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifaceMapping" eType="ecore:EClass imap.ecore#//MInterfaceMapping"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeValueAssignments"
        upperBound="-1" eType="ecore:EClass ../../es.uah.aut.srg.micobs/model/common.ecore#//MParameterValueAssignment"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MDeploymentPlatform" eSuperTypes="../../es.uah.aut.srg.micobs/model/common.ecore#//MCommonReferenceableObj">
    <eStructuralFeatures xsi:type="ecore:EReference" name="platform" lowerBound="1"
        eType="ecore:EClass ../../es.uah.aut.srg.micobs.pdl/model/pdl.ecore#//MPlatform"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterValueAssignments"
        upperBound="-1" eType="ecore:EClass ../../es.uah.aut.srg.micobs/model/common.ecore#//MParameterValueAssignment"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deployedDevices" upperBound="-1"
        eType="#//MDeployedDevice" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MDeployedDevice" eSuperTypes="../../es.uah.aut.srg.micobs/model/common.ecore#//MCommonReferenceableObj">
    <eStructuralFeatures xsi:type="ecore:EReference" name="device" lowerBound="1"
        eType="ecore:EClass ../../es.uah.aut.srg.micobs.pdl/model/pdl.ecore#//MDevice"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterValueAssignments"
        upperBound="-1" eType="ecore:EClass ../../es.uah.aut.srg.micobs/model/common.ecore#//MParameterValueAssignment"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVMCADPackageFile" eSuperTypes="../../es.uah.aut.srg.micobs/model/common.ecore#//MCommonPackageFile"/>
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVMCADPackageElement" abstract="true"
      eSuperTypes="../../es.uah.aut.srg.micobs/model/common.ecore#//MCommonPackageElement"/>
</ecore:EPackage>
