<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mclevlibrary" nsURI="http://srg.aut.uah.es/micobs/mclev/library/mclevlibrary"
    nsPrefix="micobs.mclev.library">
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVLibrary" eSuperTypes="../../es.uah.aut.srg.micobs/model/common.ecore#//MCommonLibrary"/>
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVPackage" eSuperTypes="../../es.uah.aut.srg.micobs/model/common.ecore#//MCommonPackage"/>
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVPackageItem" abstract="true" eSuperTypes="../../es.uah.aut.srg.micobs/model/common.ecore#//MCommonPackageItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVPackageVersionedItem" abstract="true"
      eSuperTypes="../../es.uah.aut.srg.micobs/model/common.ecore#//MCommonPackageVersionedItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVItemComponent" eSuperTypes="#//MMCLEVPackageItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVVersionedItemComponent" eSuperTypes="#//MMCLEVPackageVersionedItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="swPackageURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="swPackageVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="swInterfaceURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="swInterfaceVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVItemSAI" eSuperTypes="#//MMCLEVPackageItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVVersionedItemSAI" eSuperTypes="#//MMCLEVPackageVersionedItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="swInterfaceURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="swInterfaceVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVItemInterface" eSuperTypes="#//MMCLEVPackageItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVVersionedItemInterface" eSuperTypes="#//MMCLEVPackageVersionedItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVItemInterfaceMapping" eSuperTypes="#//MMCLEVPackageItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVVersionedItemInterfaceMapping"
      eSuperTypes="#//MMCLEVPackageVersionedItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVItemServiceLibrary" eSuperTypes="#//MMCLEVPackageItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVVersionedItemServiceLibrary" eSuperTypes="#//MMCLEVPackageVersionedItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="swPackageURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="swPackageVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVItemIODomain" eSuperTypes="#//MMCLEVPackageItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVVersionedItemIODomain" eSuperTypes="#//MMCLEVPackageVersionedItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVItemAODomain" eSuperTypes="#//MMCLEVPackageItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVVersionedItemAODomain" eSuperTypes="#//MMCLEVPackageVersionedItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVItemMCAD" eSuperTypes="#//MMCLEVPackageItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVVersionedItemMCAD" eSuperTypes="#//MMCLEVPackageVersionedItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVItemAbstractComponent" eSuperTypes="#//MMCLEVPackageItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVVersionedItemAbstractComponent"
      eSuperTypes="#//MMCLEVPackageVersionedItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVItemAbstractServiceLibrary" eSuperTypes="#//MMCLEVPackageItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVVersionedItemAbstractServiceLibrary"
      eSuperTypes="#//MMCLEVPackageVersionedItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVItemFlatMCAD" eSuperTypes="#//MMCLEVPackageItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVVersionedItemFlatMCAD" eSuperTypes="#//MMCLEVPackageVersionedItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVItemDriverServiceLibrary" eSuperTypes="#//MMCLEVPackageItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVVersionedItemDriverServiceLibrary"
      eSuperTypes="#//MMCLEVPackageVersionedItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="swPackageURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="swPackageVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
