<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mclevsai" nsURI="http://srg.aut.uah.es/micobs/mclev/mclevsai"
    nsPrefix="micobs.mclev">
  <eClassifiers xsi:type="ecore:EClass" name="MSAI" eSuperTypes="#//MMCLEVSAIPackageElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" upperBound="-1"
        eType="#//MSAI"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="language" lowerBound="1"
        eType="ecore:EClass ../../es.uah.aut.srg.micobs/model/system.ecore#//MLanguage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requires" upperBound="-1"
        eType="#//MSAI"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="ecore:EClass ../../es.uah.aut.srg.micobs/model/common.ecore#//MParameter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredOSAPI" eType="ecore:EClass ../../es.uah.aut.srg.micobs.pdl/model/pdl.ecore#//MOperatingSystemAPI"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVSAIPackageFile" eSuperTypes="../../es.uah.aut.srg.micobs/model/common.ecore#//MCommonPackageFile"/>
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVSAIPackageElement" abstract="true"
      eSuperTypes="../../es.uah.aut.srg.micobs/model/common.ecore#//MCommonPackageElement"/>
</ecore:EPackage>
