<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mclevslib" nsURI="http://srg.aut.uah.es/micobs/mclev/mclevslib"
    nsPrefix="micobs.mclev">
  <eClassifiers xsi:type="ecore:EClass" name="MServiceLibrary" eSuperTypes="#//MMCLEVSLIBPackageElement #//MAbstractServiceLibrary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requires" upperBound="-1"
        eType="ecore:EClass sai.ecore#//MSAI"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="languages" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../es.uah.aut.srg.micobs/model/system.ecore#//MLanguage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" upperBound="-1"
        eType="#//MServiceLibrary"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedPlatforms" lowerBound="1"
        upperBound="-1" eType="#//MServiceLibrarySupportedPlatform" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MServiceLibraryProvidedSAI">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sai" lowerBound="1" eType="ecore:EClass sai.ecore#//MSAI"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeValueAssignments"
        upperBound="-1" eType="#//MSLibProvidedSAIAVA" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MSLibProvidedSAIAVA" abstract="true"
      eSuperTypes="../../es.uah.aut.srg.micobs/model/common.ecore#//MParameterValueAssignment"/>
  <eClassifiers xsi:type="ecore:EClass" name="MSLibProvidedSAIAVASwitch" eSuperTypes="#//MSLibProvidedSAIAVA">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cases" lowerBound="1" upperBound="-1"
        eType="#//MSLibProvidedSAIAVASwitchCase" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MSLibProvidedSAIAVASwitchCase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="platform" lowerBound="1"
        eType="#//MServiceLibrarySupportedPlatform"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeValue" lowerBound="1"
        eType="ecore:EClass ../../es.uah.aut.srg.micobs/model/common.ecore#//MParameterValueExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MSLibProvidedSAIAVAExpression" eSuperTypes="#//MSLibProvidedSAIAVA">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeValue" lowerBound="1"
        eType="ecore:EClass ../../es.uah.aut.srg.micobs/model/common.ecore#//MParameterValueExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MServiceLibrarySupportedPlatform" eSuperTypes="../../es.uah.aut.srg.micobs/model/common.ecore#//MCommonReferenceableObj">
    <eStructuralFeatures xsi:type="ecore:EReference" name="osapi" eType="ecore:EClass ../../es.uah.aut.srg.micobs.pdl/model/pdl.ecore#//MOperatingSystemAPI"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="os" eType="ecore:EClass ../../es.uah.aut.srg.micobs.pdl/model/pdl.ecore#//MOperatingSystem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="architecture" eType="ecore:EClass ../../es.uah.aut.srg.micobs.pdl/model/pdl.ecore#//MArchitecture"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compiler" eType="ecore:EClass ../../es.uah.aut.srg.micobs.pdl/model/pdl.ecore#//MCompiler"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="microprocessor" eType="ecore:EClass ../../es.uah.aut.srg.micobs.pdl/model/pdl.ecore#//MMicroprocessor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="board" eType="ecore:EClass ../../es.uah.aut.srg.micobs.pdl/model/pdl.ecore#//MBoard"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requires" upperBound="-1"
        eType="ecore:EClass sai.ecore#//MSAI"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="ecore:EClass ../../es.uah.aut.srg.micobs/model/common.ecore#//MParameter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="languages" upperBound="-1"
        eType="ecore:EClass ../../es.uah.aut.srg.micobs/model/system.ecore#//MLanguage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MDriverSLibSupportedPlatform" eSuperTypes="#//MServiceLibrarySupportedPlatform">
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedDevices" upperBound="-1"
        eType="#//MDriverSLibSupportedDevice" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MDriverSLibSupportedDevice" eSuperTypes="../../es.uah.aut.srg.micobs/model/common.ecore#//MCommonReferenceableObj">
    <eStructuralFeatures xsi:type="ecore:EReference" name="required" eType="ecore:EClass ../../es.uah.aut.srg.micobs/model/common.ecore#//MParameterValueExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="device" lowerBound="1"
        eType="ecore:EClass ../../es.uah.aut.srg.micobs.pdl/model/pdl.ecore#//MDevice"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MAbstractServiceLibrary" eSuperTypes="#//MMCLEVSLIBPackageElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="ecore:EClass ../../es.uah.aut.srg.micobs/model/common.ecore#//MParameter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inherits" upperBound="-1"
        eType="#//MAbstractServiceLibrary"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="provides" upperBound="-1"
        eType="#//MServiceLibraryProvidedSAI" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVSLIBPackageFile" eSuperTypes="../../es.uah.aut.srg.micobs/model/common.ecore#//MCommonPackageFile"/>
  <eClassifiers xsi:type="ecore:EClass" name="MMCLEVSLIBPackageElement" abstract="true"
      eSuperTypes="../../es.uah.aut.srg.micobs/model/common.ecore#//MCommonPackageElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="MDriverServiceLibrary" eSuperTypes="#//MServiceLibrary"/>
  <eClassifiers xsi:type="ecore:EClass" name="MParameterSLSPSwitch" abstract="true"
      eSuperTypes="../../es.uah.aut.srg.micobs/model/common.ecore#//MParameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cases" lowerBound="1" upperBound="-1"
        eType="#//MParameterSLSPSwitchCase" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MParameterSLSPSwitchCase" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" lowerBound="1"
        eType="ecore:EClass ../../es.uah.aut.srg.micobs/model/common.ecore#//MParameterValueExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="platform" lowerBound="1"
        eType="#//MServiceLibrarySupportedPlatform"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MBooleanParamSLSPSwitch" eSuperTypes="../../es.uah.aut.srg.micobs/model/common.ecore#//MBooleanParameter #//MParameterSLSPSwitch"/>
  <eClassifiers xsi:type="ecore:EClass" name="MBooleanParamSLSPSwitchCase" eSuperTypes="#//MParameterSLSPSwitchCase"/>
  <eClassifiers xsi:type="ecore:EClass" name="MStringParamSLSPSwitch" eSuperTypes="../../es.uah.aut.srg.micobs/model/common.ecore#//MStringParameter #//MParameterSLSPSwitch"/>
  <eClassifiers xsi:type="ecore:EClass" name="MStringParamSLSPSwitchCase" eSuperTypes="#//MParameterSLSPSwitchCase"/>
  <eClassifiers xsi:type="ecore:EClass" name="MIntegerParamSLSPSwitch" eSuperTypes="../../es.uah.aut.srg.micobs/model/common.ecore#//MIntegerParameter #//MParameterSLSPSwitch"/>
  <eClassifiers xsi:type="ecore:EClass" name="MIntegerParamSLSPSwitchCase" eSuperTypes="#//MParameterSLSPSwitchCase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="range" eType="ecore:EClass ../../es.uah.aut.srg.micobs/model/common.ecore#//MParameterRange"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MEnumParamSLSPSwitch" eSuperTypes="../../es.uah.aut.srg.micobs/model/common.ecore#//MEnumParameter #//MParameterSLSPSwitch"/>
  <eClassifiers xsi:type="ecore:EClass" name="MEnumParamSLSPSwitchCase" eSuperTypes="#//MParameterSLSPSwitchCase"/>
  <eClassifiers xsi:type="ecore:EClass" name="MRealParamSLSPSwitch" eSuperTypes="../../es.uah.aut.srg.micobs/model/common.ecore#//MRealParameter #//MParameterSLSPSwitch"/>
  <eClassifiers xsi:type="ecore:EClass" name="MRealParamSLSPSwitchCase" eSuperTypes="#//MParameterSLSPSwitchCase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="range" eType="ecore:EClass ../../es.uah.aut.srg.micobs/model/common.ecore#//MParameterRange"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
