<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mesposswi" nsURI="http://srg.aut.uah.es/micobs/mesp/mesposswi"
    nsPrefix="micobs.mesp">
  <eClassifiers xsi:type="ecore:EClass" name="MOSSwInterface" eSuperTypes="#//MMESPOSSWIPackageElement ../../es.uah.aut.srg.micobs/model/common.ecore#//MCommonPackageReferencingElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" upperBound="-1"
        eType="#//MOSSwInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedResources" upperBound="-1"
        eType="ecore:EClass mespcommon.ecore#//MProvidedResource" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MMESPOSSWIPackageFile" eSuperTypes="../../es.uah.aut.srg.micobs/model/common.ecore#//MCommonPackageFile"/>
  <eClassifiers xsi:type="ecore:EClass" name="MMESPOSSWIPackageElement" abstract="true"
      eSuperTypes="../../es.uah.aut.srg.micobs/model/common.ecore#//MCommonPackageElement"/>
</ecore:EPackage>
