/*******************************************************************************
 * Copyright (c) 2013-2015 UAH Space Research Group.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     MICOBS SRG Team - Initial API and implementation
 ******************************************************************************/
package es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.util.edroomdclassAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * @generated
 */
public class edroomdclassItemProviderAdapterFactory extends edroomdclassAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * @generated
	 */
	public edroomdclassItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataClass} instances.
	 * @generated
	 */
	protected EDROOMDataClassItemProvider edroomDataClassItemProvider;

	/**
	 * This creates an adapter for a {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataClass}.
	 * @generated
	 */
	@Override
	public Adapter createEDROOMDataClassAdapter() {
		if (edroomDataClassItemProvider == null) {
			edroomDataClassItemProvider = new EDROOMDataClassItemProvider(this);
		}

		return edroomDataClassItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataFieldBasic} instances.
	 * @generated
	 */
	protected EDROOMDataFieldBasicItemProvider edroomDataFieldBasicItemProvider;

	/**
	 * This creates an adapter for a {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataFieldBasic}.
	 * @generated
	 */
	@Override
	public Adapter createEDROOMDataFieldBasicAdapter() {
		if (edroomDataFieldBasicItemProvider == null) {
			edroomDataFieldBasicItemProvider = new EDROOMDataFieldBasicItemProvider(this);
		}

		return edroomDataFieldBasicItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataFieldBasicArray} instances.
	 * @generated
	 */
	protected EDROOMDataFieldBasicArrayItemProvider edroomDataFieldBasicArrayItemProvider;

	/**
	 * This creates an adapter for a {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataFieldBasicArray}.
	 * @generated
	 */
	@Override
	public Adapter createEDROOMDataFieldBasicArrayAdapter() {
		if (edroomDataFieldBasicArrayItemProvider == null) {
			edroomDataFieldBasicArrayItemProvider = new EDROOMDataFieldBasicArrayItemProvider(this);
		}

		return edroomDataFieldBasicArrayItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataFieldClass} instances.
	 * @generated
	 */
	protected EDROOMDataFieldClassItemProvider edroomDataFieldClassItemProvider;

	/**
	 * This creates an adapter for a {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataFieldClass}.
	 * @generated
	 */
	@Override
	public Adapter createEDROOMDataFieldClassAdapter() {
		if (edroomDataFieldClassItemProvider == null) {
			edroomDataFieldClassItemProvider = new EDROOMDataFieldClassItemProvider(this);
		}

		return edroomDataFieldClassItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataFieldClassArray} instances.
	 * @generated
	 */
	protected EDROOMDataFieldClassArrayItemProvider edroomDataFieldClassArrayItemProvider;

	/**
	 * This creates an adapter for a {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataFieldClassArray}.
	 * @generated
	 */
	@Override
	public Adapter createEDROOMDataFieldClassArrayAdapter() {
		if (edroomDataFieldClassArrayItemProvider == null) {
			edroomDataFieldClassArrayItemProvider = new EDROOMDataFieldClassArrayItemProvider(this);
		}

		return edroomDataFieldClassArrayItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataFieldUnionArray} instances.
	 * @generated
	 */
	protected EDROOMDataFieldUnionArrayItemProvider edroomDataFieldUnionArrayItemProvider;

	/**
	 * This creates an adapter for a {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataFieldUnionArray}.
	 * @generated
	 */
	@Override
	public Adapter createEDROOMDataFieldUnionArrayAdapter() {
		if (edroomDataFieldUnionArrayItemProvider == null) {
			edroomDataFieldUnionArrayItemProvider = new EDROOMDataFieldUnionArrayItemProvider(this);
		}

		return edroomDataFieldUnionArrayItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataFieldUnion} instances.
	 * @generated
	 */
	protected EDROOMDataFieldUnionItemProvider edroomDataFieldUnionItemProvider;

	/**
	 * This creates an adapter for a {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataFieldUnion}.
	 * @generated
	 */
	@Override
	public Adapter createEDROOMDataFieldUnionAdapter() {
		if (edroomDataFieldUnionItemProvider == null) {
			edroomDataFieldUnionItemProvider = new EDROOMDataFieldUnionItemProvider(this);
		}

		return edroomDataFieldUnionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataFieldEnumArray} instances.
	 * @generated
	 */
	protected EDROOMDataFieldEnumArrayItemProvider edroomDataFieldEnumArrayItemProvider;

	/**
	 * This creates an adapter for a {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataFieldEnumArray}.
	 * @generated
	 */
	@Override
	public Adapter createEDROOMDataFieldEnumArrayAdapter() {
		if (edroomDataFieldEnumArrayItemProvider == null) {
			edroomDataFieldEnumArrayItemProvider = new EDROOMDataFieldEnumArrayItemProvider(this);
		}

		return edroomDataFieldEnumArrayItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataFieldEnum} instances.
	 * @generated
	 */
	protected EDROOMDataFieldEnumItemProvider edroomDataFieldEnumItemProvider;

	/**
	 * This creates an adapter for a {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataFieldEnum}.
	 * @generated
	 */
	@Override
	public Adapter createEDROOMDataFieldEnumAdapter() {
		if (edroomDataFieldEnumItemProvider == null) {
			edroomDataFieldEnumItemProvider = new EDROOMDataFieldEnumItemProvider(this);
		}

		return edroomDataFieldEnumItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataDefinitionUnion} instances.
	 * @generated
	 */
	protected EDROOMDataDefinitionUnionItemProvider edroomDataDefinitionUnionItemProvider;

	/**
	 * This creates an adapter for a {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataDefinitionUnion}.
	 * @generated
	 */
	@Override
	public Adapter createEDROOMDataDefinitionUnionAdapter() {
		if (edroomDataDefinitionUnionItemProvider == null) {
			edroomDataDefinitionUnionItemProvider = new EDROOMDataDefinitionUnionItemProvider(this);
		}

		return edroomDataDefinitionUnionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataDefinitionUnionElementBasic} instances.
	 * @generated
	 */
	protected EDROOMDataDefinitionUnionElementBasicItemProvider edroomDataDefinitionUnionElementBasicItemProvider;

	/**
	 * This creates an adapter for a {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataDefinitionUnionElementBasic}.
	 * @generated
	 */
	@Override
	public Adapter createEDROOMDataDefinitionUnionElementBasicAdapter() {
		if (edroomDataDefinitionUnionElementBasicItemProvider == null) {
			edroomDataDefinitionUnionElementBasicItemProvider = new EDROOMDataDefinitionUnionElementBasicItemProvider(this);
		}

		return edroomDataDefinitionUnionElementBasicItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataDefinitionUnionElementClass} instances.
	 * @generated
	 */
	protected EDROOMDataDefinitionUnionElementClassItemProvider edroomDataDefinitionUnionElementClassItemProvider;

	/**
	 * This creates an adapter for a {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataDefinitionUnionElementClass}.
	 * @generated
	 */
	@Override
	public Adapter createEDROOMDataDefinitionUnionElementClassAdapter() {
		if (edroomDataDefinitionUnionElementClassItemProvider == null) {
			edroomDataDefinitionUnionElementClassItemProvider = new EDROOMDataDefinitionUnionElementClassItemProvider(this);
		}

		return edroomDataDefinitionUnionElementClassItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataDefinitionUnionElementBasicArray} instances.
	 * @generated
	 */
	protected EDROOMDataDefinitionUnionElementBasicArrayItemProvider edroomDataDefinitionUnionElementBasicArrayItemProvider;

	/**
	 * This creates an adapter for a {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataDefinitionUnionElementBasicArray}.
	 * @generated
	 */
	@Override
	public Adapter createEDROOMDataDefinitionUnionElementBasicArrayAdapter() {
		if (edroomDataDefinitionUnionElementBasicArrayItemProvider == null) {
			edroomDataDefinitionUnionElementBasicArrayItemProvider = new EDROOMDataDefinitionUnionElementBasicArrayItemProvider(this);
		}

		return edroomDataDefinitionUnionElementBasicArrayItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataDefinitionUnionElementClassArray} instances.
	 * @generated
	 */
	protected EDROOMDataDefinitionUnionElementClassArrayItemProvider edroomDataDefinitionUnionElementClassArrayItemProvider;

	/**
	 * This creates an adapter for a {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataDefinitionUnionElementClassArray}.
	 * @generated
	 */
	@Override
	public Adapter createEDROOMDataDefinitionUnionElementClassArrayAdapter() {
		if (edroomDataDefinitionUnionElementClassArrayItemProvider == null) {
			edroomDataDefinitionUnionElementClassArrayItemProvider = new EDROOMDataDefinitionUnionElementClassArrayItemProvider(this);
		}

		return edroomDataDefinitionUnionElementClassArrayItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataDefinitionUnionElementUnion} instances.
	 * @generated
	 */
	protected EDROOMDataDefinitionUnionElementUnionItemProvider edroomDataDefinitionUnionElementUnionItemProvider;

	/**
	 * This creates an adapter for a {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataDefinitionUnionElementUnion}.
	 * @generated
	 */
	@Override
	public Adapter createEDROOMDataDefinitionUnionElementUnionAdapter() {
		if (edroomDataDefinitionUnionElementUnionItemProvider == null) {
			edroomDataDefinitionUnionElementUnionItemProvider = new EDROOMDataDefinitionUnionElementUnionItemProvider(this);
		}

		return edroomDataDefinitionUnionElementUnionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataDefinitionUnionElementUnionArray} instances.
	 * @generated
	 */
	protected EDROOMDataDefinitionUnionElementUnionArrayItemProvider edroomDataDefinitionUnionElementUnionArrayItemProvider;

	/**
	 * This creates an adapter for a {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataDefinitionUnionElementUnionArray}.
	 * @generated
	 */
	@Override
	public Adapter createEDROOMDataDefinitionUnionElementUnionArrayAdapter() {
		if (edroomDataDefinitionUnionElementUnionArrayItemProvider == null) {
			edroomDataDefinitionUnionElementUnionArrayItemProvider = new EDROOMDataDefinitionUnionElementUnionArrayItemProvider(this);
		}

		return edroomDataDefinitionUnionElementUnionArrayItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataDefinitionEnum} instances.
	 * @generated
	 */
	protected EDROOMDataDefinitionEnumItemProvider edroomDataDefinitionEnumItemProvider;

	/**
	 * This creates an adapter for a {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataDefinitionEnum}.
	 * @generated
	 */
	@Override
	public Adapter createEDROOMDataDefinitionEnumAdapter() {
		if (edroomDataDefinitionEnumItemProvider == null) {
			edroomDataDefinitionEnumItemProvider = new EDROOMDataDefinitionEnumItemProvider(this);
		}

		return edroomDataDefinitionEnumItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataDefinitionEnumElement} instances.
	 * @generated
	 */
	protected EDROOMDataDefinitionEnumElementItemProvider edroomDataDefinitionEnumElementItemProvider;

	/**
	 * This creates an adapter for a {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataDefinitionEnumElement}.
	 * @generated
	 */
	@Override
	public Adapter createEDROOMDataDefinitionEnumElementAdapter() {
		if (edroomDataDefinitionEnumElementItemProvider == null) {
			edroomDataDefinitionEnumElementItemProvider = new EDROOMDataDefinitionEnumElementItemProvider(this);
		}

		return edroomDataDefinitionEnumElementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataDefinitionUnionElementEnum} instances.
	 * @generated
	 */
	protected EDROOMDataDefinitionUnionElementEnumItemProvider edroomDataDefinitionUnionElementEnumItemProvider;

	/**
	 * This creates an adapter for a {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataDefinitionUnionElementEnum}.
	 * @generated
	 */
	@Override
	public Adapter createEDROOMDataDefinitionUnionElementEnumAdapter() {
		if (edroomDataDefinitionUnionElementEnumItemProvider == null) {
			edroomDataDefinitionUnionElementEnumItemProvider = new EDROOMDataDefinitionUnionElementEnumItemProvider(this);
		}

		return edroomDataDefinitionUnionElementEnumItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataDefinitionUnionElementEnumArray} instances.
	 * @generated
	 */
	protected EDROOMDataDefinitionUnionElementEnumArrayItemProvider edroomDataDefinitionUnionElementEnumArrayItemProvider;

	/**
	 * This creates an adapter for a {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDataDefinitionUnionElementEnumArray}.
	 * @generated
	 */
	@Override
	public Adapter createEDROOMDataDefinitionUnionElementEnumArrayAdapter() {
		if (edroomDataDefinitionUnionElementEnumArrayItemProvider == null) {
			edroomDataDefinitionUnionElementEnumArrayItemProvider = new EDROOMDataDefinitionUnionElementEnumArrayItemProvider(this);
		}

		return edroomDataDefinitionUnionElementEnumArrayItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDCLASSPackageFile} instances.
	 * @generated
	 */
	protected EDROOMDCLASSPackageFileItemProvider edroomdclassPackageFileItemProvider;

	/**
	 * This creates an adapter for a {@link es.uah.aut.srg.micobs.mclev.domain.edroom.edroomdclass.EDROOMDCLASSPackageFile}.
	 * @generated
	 */
	@Override
	public Adapter createEDROOMDCLASSPackageFileAdapter() {
		if (edroomdclassPackageFileItemProvider == null) {
			edroomdclassPackageFileItemProvider = new EDROOMDCLASSPackageFileItemProvider(this);
		}

		return edroomdclassPackageFileItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory.
	 * @generated
	 */
	public void dispose() {
		if (edroomDataClassItemProvider != null) edroomDataClassItemProvider.dispose();
		if (edroomDataFieldBasicItemProvider != null) edroomDataFieldBasicItemProvider.dispose();
		if (edroomDataFieldBasicArrayItemProvider != null) edroomDataFieldBasicArrayItemProvider.dispose();
		if (edroomDataFieldClassItemProvider != null) edroomDataFieldClassItemProvider.dispose();
		if (edroomDataFieldClassArrayItemProvider != null) edroomDataFieldClassArrayItemProvider.dispose();
		if (edroomDataFieldUnionArrayItemProvider != null) edroomDataFieldUnionArrayItemProvider.dispose();
		if (edroomDataFieldUnionItemProvider != null) edroomDataFieldUnionItemProvider.dispose();
		if (edroomDataFieldEnumArrayItemProvider != null) edroomDataFieldEnumArrayItemProvider.dispose();
		if (edroomDataFieldEnumItemProvider != null) edroomDataFieldEnumItemProvider.dispose();
		if (edroomDataDefinitionUnionItemProvider != null) edroomDataDefinitionUnionItemProvider.dispose();
		if (edroomDataDefinitionUnionElementBasicItemProvider != null) edroomDataDefinitionUnionElementBasicItemProvider.dispose();
		if (edroomDataDefinitionUnionElementClassItemProvider != null) edroomDataDefinitionUnionElementClassItemProvider.dispose();
		if (edroomDataDefinitionUnionElementBasicArrayItemProvider != null) edroomDataDefinitionUnionElementBasicArrayItemProvider.dispose();
		if (edroomDataDefinitionUnionElementClassArrayItemProvider != null) edroomDataDefinitionUnionElementClassArrayItemProvider.dispose();
		if (edroomDataDefinitionUnionElementUnionItemProvider != null) edroomDataDefinitionUnionElementUnionItemProvider.dispose();
		if (edroomDataDefinitionUnionElementUnionArrayItemProvider != null) edroomDataDefinitionUnionElementUnionArrayItemProvider.dispose();
		if (edroomDataDefinitionEnumItemProvider != null) edroomDataDefinitionEnumItemProvider.dispose();
		if (edroomDataDefinitionEnumElementItemProvider != null) edroomDataDefinitionEnumElementItemProvider.dispose();
		if (edroomDataDefinitionUnionElementEnumItemProvider != null) edroomDataDefinitionUnionElementEnumItemProvider.dispose();
		if (edroomDataDefinitionUnionElementEnumArrayItemProvider != null) edroomDataDefinitionUnionElementEnumArrayItemProvider.dispose();
		if (edroomdclassPackageFileItemProvider != null) edroomdclassPackageFileItemProvider.dispose();
	}

}
