/*
 * generated by Xtext
 */
package es.uah.aut.srg.micobs.lang.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import es.uah.aut.srg.micobs.lang.ui.internal.LANGActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LANGExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return LANGActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return LANGActivator.getInstance().getInjector(LANGActivator.ES_UAH_AUT_SRG_MICOBS_LANG_LANG);
	}
	
}
