/*
* generated by Xtext
*/
package es.uah.aut.srg.micobs.mesp.lang.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class OSSWPAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("es/uah/aut/srg/micobs/mesp/lang/parser/antlr/internal/InternalOSSWP.tokens");
	}
}
